# Generated by Django 5.2.5 on 2025-09-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('uf', models.CharField(choices=[('AL', 'Alagoas'), ('AC', 'Acre'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia')], max_length=2, verbose_name='UF')),
            ],
        ),
    ]
