# Generated by Django 5.2.5 on 2025-09-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=15, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20, unique=True, verbose_name='Senha'),
        ),
    ]
