# Generated by Django 5.2.5 on 2025-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_delete_pessoa_alter_usuario_cpf_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='uf',
            field=models.CharField(choices=[('AL', 'Alagoas'), ('AC', 'Acre'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará')], max_length=2, verbose_name='UF'),
        ),
    ]
