# Generated by Django 5.2.5 on 2025-09-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_usuario_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
