# Generated by Django 5.2.5 on 2025-09-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='uf',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(choices=[('AL', 'Alagoas'), ('AC', 'Acre'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará')], max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=29, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('n', models.CharField(max_length=10, verbose_name='N°')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento(opcional)')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
            ],
        ),
    ]
