# Generated by Django 5.2.5 on 2025-09-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_remove_usuario_uf_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Transgênero', 'Transgênero'), ('Não binário', 'Não binário')], default=None, max_length=11, verbose_name='Gênero'),
            preserve_default=False,
        ),
    ]
