# Generated by Django 5.2.5 on 2025-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('Padrão', 'Padrão'), ('Admin', 'Admin'), ('Gestor', 'Gestor')], default='Padrão', verbose_name='Nivel de usuario:'),
            preserve_default=False,
        ),
    ]
