# Generated by Django 5.2.5 on 2025-10-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_usuario_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('Padrão', 'Padrão'), ('Gestor', 'Gestor')], verbose_name='Nivel de usuario:'),
        ),
    ]
