# Generated by Django 5.2.5 on 2025-10-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cliente_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='principal.usuario'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.CharField(blank=True, max_length=5, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
