# Generated by Django 5.2.5 on 2025-10-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_alter_endereco_cliente_id_alter_endereco_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=72, unique=True, verbose_name='Senha'),
        ),
    ]
